### ISSUE TITLE
Data Sharing between Accounts fails at Getting Table of Content from <Char>

### ISSUE THREAD

**Issue by prathmell** [teelolws/Altoholic-Classic#12] opened 2020-02-15 21:11 UTC
I have 2 WoW accounts under the same Battle.net account  I have set up all chars on both accounts to share everything.  I have disabled all other addins except for Addin Control Panel, logged out of both accounts and rebooted the computer.
Steps to reproduce (CharA is on acct A and CharB on acct B):
CharA presses button to request sharing
   Dialog box appears with _Send Request_ and _Cancel_ buttons, field for Account Name, and optons for character name, and a check box for  _All_  available content
   CharA names the account (Foo) and names CharB on Acct B (who is in game and near CharA) and checks the    _All_ box
   _Getting table of content from CharB_ shows in the dialog
   CharA presses  _Send Request_ button
CharB receives dialog box with the request from CharA to share (sharing is enabled at the "?" level, 
   Dialog contains a warning and two buttons _Yes_ and _No_ which highlight when moused-over
   CharB presses _Yes_ but there is no graphic or other indication that the button is actually activated.
CharA does not receive any data transfer.
I have kept the windows open for at least 20 minutes to allow for delay and lag

**Comment by teelolws** [comment] 2020-02-15 21:23
Unfortunately, I can't actually fix or even test Data Sharing because I don't have two accounts myself! The changes that were made to Data Sharing here were by another user who forked my repository. Sorry, but its an issue I simply can't fix because I don't have two accounts.

**Comment by prathmell** [comment] 2020-02-15 21:26
Completely understand.  The version I have must be the fork, because the offending datastore items as referenced in the closed issue have been removed, and the button to share data is there, not commented out.

**Comment by prathmell** [comment] 2020-02-15 21:26
I do want to tell you how much I appreciate your efforts to get this (my favorite) addon restored to Classic.

**Comment by teelolws** [comment] 2020-02-15 21:34
Not sure what you mean. The account share button shouldn't be commented out? Thaoky commented it out when he released his version of Classic, I uncommented it when I merged in his changes.

**Comment by prathmell** [comment] 2020-02-15 21:39
I must have misread the closed issue. is there a fork I can test that's not on the main Twitch/Curse site?

**Comment by prathmell** [comment] 2020-02-15 21:40
I wonder if you could test using a bank char on another account.  You don't actually have to own 2 accounts, just have a friendly guildie who is willing to share data on one of his chars with you.

**Comment by teelolws** [comment] 2020-02-15 21:42
If you're on the US region, add Teelo#1968 and I can do some testing with you a bit later today. I'm currently working on getting Datastore_Crafts to track Enchanting properly. Having some issues with it.

**Comment by CZX6** [comment] 2020-02-15 23:54
I'm having the same issue... deleted from addons and installed old 8.0.001 and was able to get the table of contents, but some of the buttons/lists/content was not visible with 8.0.001.

**Comment by teelolws** [comment] 2020-02-16 01:44
I'm on a roadblock with this issue. I went as far as tried this entire Altoholic-Classic build on my Retail client and the account sharing actually worked.

**Comment by teelolws** [comment] 2020-02-16 02:34
It seems to fail randomly, and I've even had it disconnect my client a couple of times. Unfortunately, this seems to be beyond me. Its just too difficult to test for where the problem is when I don't have two accounts.

I've got it to a point where it will **usually** succeed in sharing data for one character and one module at a time. It just gets stuck trying to send more.

**Comment by CZX6** [comment] 2020-02-17 16:44
Any progress?  Will to help by sending data or character sharing if needed.  I'm no developer :)

**Comment by teelolws** [comment] 2020-02-17 18:26
Sorry, I can't work on this. I don't have two accounts.

**Comment by grahamers2002** [comment] 2020-02-21 21:40
Can I pay for a second account for your for a month?   I will set it up and give you access, if that helps.

**Comment by teelolws** [comment] 2020-02-21 21:43
No, because then I'll feel obligated to actually fix it. I spend some time on it last week and couldn't make sense of how it works.

The retail version is having similar issues, if I can figure out why then I might be able to apply the same fix here.

**Comment by teelolws** [comment] 2020-02-22 01:56
Allright, I take back what I said about Retail. I just tried a transfer of a massive amount of data. It took almost an hour but the transfer completed in the end. I feel like there must be a bug in the classic version either with the library used to split up whispers, or one of the messages is being sent out and never getting an acknowledgment back.

**Comment by teelolws** [comment] 2020-03-02 21:20
I've found what might have been causing it to break, and am uploading the fix now. Can you test it out?

I did notice that the Account Sharing Enabled box had to be checked, **even on the character sending the request**. It doesn't make much sense to me for the sender to need it, but that seems to be how the code works. It still let me send the request, it just never accepted the data received while it was disabled. 

![image](https://user-images.githubusercontent.com/49792789/75718838-83435080-5d38-11ea-8e34-9a3930d518fc.png)

**Comment by teelolws** [comment] 2020-03-02 21:26
If you still get problems with it, can you .zip up your Altoholic and Datastore saved variable files from World of Warcraft Classic\_classic_\WTF\Account\ _ACCOUNTNAME_ \SavedVariables
and send them to me privately. I don't think Github has a private message feature, but Curseforge does.

I wasn't having issues sending the data about my characters, so there might be something with one of your characters that needs fixing. I can simply test sharing your savedvariables to look for the problem.

**Comment by CZX6** [comment] 2020-03-02 21:42
It seems to be working now... Haven't completely gone through the data, but the transfers completed with some errors.

Date: 2020-03-02 15:30:34
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DataStore\DataStore.lua line 712:
   assertion failed!
Debug:
   [C]: assert()
   DataStore\DataStore.lua:712: GetCharacterTable()
   Altoholic\Comm.lua:396: ?()
   Altoholic\Comm.lua:165: ?()
   Altoholic\Comm.lua:129: ?()
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:264:
      ...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Altoholic, vClassic v1.13.2-011
  AltoholicSummary, vr191
  Atlas, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.6
  AtlasLootClassicData, vv1.4.6
  AtlasLootClassicDungeonsAndRaids, vv1.4.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BlueShamans, v
  ClassicCastbars, vv1.2.8
  ClassicCastbarsOptions, v
  ClickLinks, v1.0.8
  DataStore, vr66
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DBMCore, v1.13.38
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.1
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.1.6
  Guidelime, v1.040
  GuidelimeBusteas160leveling, v1.9.1-Release
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  KHunterTimers, v1.1-classic
  LeatrixMaps, v1.13.50
  LeatrixPlus, v1.13.51
  MonolithDKP, v2.1.2
  MoreStopwatches, vv1.15c
  NugComboBar, v1.13.4
  Pawn, v2.3.23
  Questie, v5.7.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.11
  ZPerl, v5.9.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=81f)

**Comment by teelolws** [comment] 2020-03-02 21:59
Hmm. I was getting that error when some DataStore_Stats code had slipped through. But after I removed it, that error stopped. Are you sure you grabbed all the files I changed?

If you did, can you open up Datastore\\Datastore.lua, and add this to line 711:

`    if (type(module) ~= "table") then print("Error: module isn't a table. Its value is: ", module) end`

Test it again, and show me what it outputs when you get the error?

**Comment by CZX6** [comment] 2020-03-02 22:21
Where can I grab the files you changed? :)  I'm not seeing the new files on
Github, and the Curseforge has version 1.13.3 (Feb. 20 2020)

**Comment by CZX6** [comment] 2020-03-02 22:24
I think I found them

**Comment by teelolws** [comment] 2020-03-02 22:27
Here on github https://github.com/teelolws/Altoholic-Classic
"Clone or Download" --> Download ZIP.

I'm not uploading them to Curseforge when I don't know if it fixed anything.

**Comment by CZX6** [comment] 2020-03-02 22:30
Giddy Up!

I think you've fixed it, fine sir!  

It's taking some time to transfer from my main account to alt account, but not getting any errors.  Transferring from alt account to main account (much less data) it completed successfully with no errors.

Job well done, it appears. Kudos.

**Comment by teelolws** [comment] 2020-03-02 22:31
Blizzard rate-limits addon whispers, theres nothing I can do about that. Its a problem on retail, too. Only worse, because Altoholic-Retail has way more data to share.

**Closed** 2020-03-03 00:39 UTC
Labels: bug, fixconfirmation, help wanted
